In [83]:
from bs4 import BeautifulSoup
import pandas as pd
import requests
url_a="https://books.toscrape.com/catalogue/page-"
url_b=".html"
df=pd.DataFrame({
    #"id":[],
    "book_name":[],
    "price":[],
    "stock":[],
    "url":[]
})
for i in range(1,51):
    url=url_a+f"{i}"+url_b
    r=requests.get(url, verify=True, timeout=10)
    s=BeautifulSoup(r.content,"html.parser")
    divs=s.find_all('article', class_='product_pod')
    for div in divs:
        quote={}
        quote["price"]=div.find('p', class_='price_color').text
        if (str(div.find('p',class_='instock availability').text).strip())=="In stock":
            quote["stock"]=1
        else:
            quote["stock"]=0
        quote["url"]=("https://books.toscrape.com/"+div.find('a').get("href"))
        quote["book_name"]=(div.find('h3').text)
        df.loc[len(df)]=quote
df.index.name="id"
df

,book_name,price,stock,url
id,,,,
0,A Light in the ...,£51.77,1,https://books.toscrape.com/a-light-in-the-atti...
1,Tipping the Velvet,£53.74,1,https://books.toscrape.com/tipping-the-velvet_...
2,Soumission,£50.10,1,https://books.toscrape.com/soumission_998/inde...
3,Sharp Objects,£47.82,1,https://books.toscrape.com/sharp-objects_997/i...
4,Sapiens: A Brief History ...,£54.23,1,https://books.toscrape.com/sapiens-a-brief-his...
...,...,...,...,...
995,Alice in Wonderland (Alice's ...,£55.53,1,https://books.toscrape.com/alice-in-wonderland...
996,"Ajin: Demi-Human, Volume 1 ...",£57.06,1,https://books.toscrape.com/ajin-demi-human-vol...
997,A Spy's Devotion (The ...,£16.97,1,https://books.toscrape.com/a-spys-devotion-the...
998,1st to Die (Women's ...,£53.98,1,https://books.toscrape.com/1st-to-die-womens-m...
999,"1,000 Places to See ...",£26.08,1,https://books.toscrape.com/1000-places-to-see-...